default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: currency_converter_app_development

test:
  <<: *default
  database: currency_converter_app_test

production:
  <<: *default
  database: currency_converter_app_production
  username: currency_converter_app
  password: <%= ENV["CURRENCY_CONVERTER_APP_DATABASE_PASSWORD"] %>
